title:              Ambika Kandel
email:              kandelambika34@gmail.com
description:        A Blog site by Ambika Kandel
author:             Ambika Kandel
baseurl:            ""
url:                "https://kandelambika34.github.io"

# Social Profiles
twitter_username:   kandel_123
# github_username:    StartBootstrap
facebook_username:  kandelambika33
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site



defaults:
  - scope:
      path: "" 
      type: "posts" 
    values:
      layout: "post"
      subtitle: ""
      background: ""
      date: 2024-06-23 22:35:45 +0545


jekyll_admin:
  hidden_links:
    - pages
    - datafiles
    - configuration

